app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('hotel.urls', 'hotel'), namespace='hotel')),
    path('caja/', include('caja.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

caja/urls.py
from django.urls import path
from .views import  Till_Detail, Item_Create, Payment_Create, Item_Delete, Payment_Delete

app_name='caja'

urlpatterns = [ 
        path('till/<int:pk>/', Till_Detail.as_view(), name='till'),
        path('create-item/', Item_Create.as_view(), name='item_create'),
        path('create-payment/', Payment_Create.as_view(), name='payment_create'),
        path('delete-item/<int:pk>/', Item_Delete.as_view(), name='delete-item'),
        path('delete-payment/<int:pk>/', Payment_Delete.as_view(), name='delete-payment'),


]

hotel/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import Home, CustomLoginView, SingUpView,  PassangerEditarView, ShowPassData, UpdateReservationView, ShowRooms, RoomEditarView, CreateReservation, CreatePasanger,UpdateReservationViewSearch, Base
from utils.ticket import export_pdf
from utils.utils import room_checkout, room_clean, room_blocked, room_dirty, searchView, check_in, no_show



urlpatterns = [
    path('', Home.as_view(), name='home'),

    # user
    path('login/', CustomLoginView.as_view(template_name = 'login.html'), name = 'login'),
    path('register/', SingUpView.as_view(), name='register'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'login.html'), name='logout'),

    # passanger info passanger.html
    path('pass-info/<int:pk>', ShowPassData.as_view(), name = 'passanger-data'),
    path('update/<int:pk>', PassangerEditarView.as_view(), name='update'),

    #reservations edit in index.html
    path('reservations/update/<int:pk>', UpdateReservationView.as_view(), name='update_reserva'),
    #create reservation
    path('create-reservation/', CreateReservation.as_view(), name = 'create_reservation'),
    #create passanger in reservation.html modal
    path('create-passenger/', CreatePasanger.as_view(), name='create-passenger'),
    
    #Rooms
    path('rooms/', ShowRooms.as_view(), name='room'),
    path('room/<int:pk>', RoomEditarView.as_view(), name='update_room'),
    #status buttons in room.html
    path('room/clean/<int:pk>', room_clean, name='room_clean'),
    path('room/blocked/<int:pk>', room_blocked, name='room_blocked'),
    path('room/dirty/<int:pk>', room_dirty, name='room_dirty'),

    #utils
    path('pdf/<int:pk>/', export_pdf, name='export_pdf'),
    path('checkout/<int:pk>', room_checkout, name='checkout'),
    #search 
    path('search/', searchView, name='search'),
    path('search/check_in/<int:pk>', check_in, name='checkin'),
    path('search/no_show/<int:pk>', no_show, name='noshow'),
    path('search_update/<int:pk>', UpdateReservationViewSearch.as_view(), name='search_update'),

    path('base/', Base.as_view(), name='base')
    ]

hotel/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from shortuuid.django_fields import ShortUUIDField
from django.db.models.signals import post_save
from django.dispatch import receiver


class Passanger(models.Model):
    name = models.CharField(max_length=205)
    dni = models.CharField(max_length=205)
    tel = models.CharField(max_length=205)
    country = models.CharField(max_length=205, null=True, blank=True)
    city  = models.CharField(max_length=205, null=True, blank=True)
    adress  = models.CharField(max_length=205, null=True, blank=True)
    email = models.CharField(max_length=205, null=True, blank=True)
    birth_date = models.DateField()
    observations = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Room(models.Model):
    STATE_STATE=(  
        (1, 'free'),
        (2, 'occupied'),
        )   
    STATUS_COLOR=(
        ('#9bf0ac', 'clean'), # clean 
        ('#fffb8f', 'dirty'), # dirty 
        ('#D47777', 'blocked'),  # blocked 
    )
    TYPES_ROOMS=(
        ('1', 'Sgl'),
        ('2', 'Dbl'),
        ('3', 'Tpl'),
        ('4', 'Qdpl'),
    )
    
    max_capacity = models.CharField(max_length=205)
    name = models.CharField(max_length=205)
    type_room = models.CharField(max_length=4, choices=TYPES_ROOMS, default='1') 
    state = models.IntegerField(choices=STATE_STATE, default=1)
    status = models.CharField(max_length=7, choices=STATUS_COLOR, default='#9bf0ac')
    observations = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Reservation(models.Model):
    STATUS_RESERVATION=(
            (1, 'reserved'),
            (2, 'check-in'),
            (3, 'check-out'),
            (4, 'no-show'),
        )
    TYPES_ROOMS=(
        ('1', 'Sgl'),
        ('2', 'Dbl'),
        ('3', 'Tpl'),
        ('4', 'Qdpl'),
    )
    
    passanger = models.ForeignKey(Passanger, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, blank=True,null=True, default=None)
    type_res = models.CharField(max_length=4, choices=TYPES_ROOMS, default='1')
    date_in = models.DateField()
    date_out = models.DateField()
    number = ShortUUIDField(length=6)
    amount_people = models.IntegerField()
    status_res = models.IntegerField(choices=STATUS_RESERVATION, default = 'not-reserved')
    observations = models.TextField()

@receiver(post_save, sender=Reservation)
def create_till_for_reservation(sender, instance, created, **kwargs):
    from caja.models import Till
    if created:
        # Si la Reservation acaba de ser creada, creamos un Till asociado
        Till.objects.create(till_res=instance)

templates/index.html
{% extends 'base.html' %}


{% block content %}

<div class="title text-center"><h2>Rooms:</h2></div>
 <!-- Room Cards --> 
<div class="row m-4 ">
    <div class="col d-flex justify-content-center flex-wrap">
        
        
        {% for room in rooms %}
        <div class="card m-3" style=" min-height: 280px; background-color:{{room.status}}; min-width: 200px; max-width: 260px;">
            <div class="card-body">
                <!-- Upper Room Card --> 
                <div class="card-top d-flex border-bottom">
                    <p class="card-state mr-2">
                        {% if room.state == 1 %}
                            Free  
                        
                        {% elif room.state == 2 %}
                            Occu. 
                        {% else %}
                            Blocked  
                        {% endif %}                    
                    
                    <p class="ml-2">Room: <strong>{{room.name}}</strong></p>                    
                    <p class='room-type ml-4'> Type: {{room.get_type_room_display}} </p>
                    
                    
                </div>
                <!-- Down part Room Card --> 
                <div class="fecha my-3">                    
                    {% for reservation in reservations %}
                        {% if reservation.room.name == room.name %}                      
                            
                            <a href="{% url 'hotel:passanger-data' pk=reservation.passanger.id %}" >- {{reservation.passanger}}</a>
                            <p class='mb-1 mt-2 font-monospace'>-In: {{reservation.date_in|date:"d-m-Y"}}</p>
                            <p class='mb-1 font-monospace'>-Out: {{reservation.date_out|date:"d-m-Y"}}</p>
                            <p class='room-type'>-Paxs: {{reservation.amount_people}}</p>

                            <!-- Check out button --> 
                            <div class="container d-flex justify-content-start flex-wrap" style="width: 300px; margin-left: -20px;">

                                <div class="checkout bg-danger rounded pt-1 text-center" >
                                    <a href="{% url 'hotel:checkout' pk=reservation.id %}"  class="mt-2 text-left"style="font-size:12px; font-weight:bold; color:#fff;">Check-out</a>
                                </div>
                                
                                <!-- Edit reservation button --> 
                                <form action="{% url 'hotel:update_reserva' pk=reservation.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="button" class="btn btn-warning ml-4" data-bs-toggle="modal" data-bs-target="#updateModal_{{reservation.id}}">
                                        Edit
                                    </button>
                                </form>

                                
                                <div class="m-2">
                                    <a href="{% url 'hotel:export_pdf' pk=reservation.id %}" target="_blank">Open PDF</a>
                                </div>

                              <!-- Reservation TILL -->  
                              <div class="mt-2">
                                {% for till in tills %}
                                    {% if till.till_res.number == reservation.number%}
                                    <a href="{% url 'caja:till' pk=till.till_res.id %}" class="btn btn-warning" target="_blank">
                                        Till
                                    </a>
                                    {% endif %}
                                                           
                               {% endfor %}
                              </div>
                               
                            </div>
                            
                        {% endif %}         
                        
                    {% endfor %}
                </div>
                    
                </div>

            </div>
        {% endfor %}
    </div>
</div>


<!--Reservation modal upate -->
{% for reservation in reservations %}
<div class="modal fade" id="updateModal_{{reservation.id}}" tabindex="-1" aria-labelledby="exampleModalLabel{{reservation.id}}" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel"><i class="bi bi-journal-bookmark"></i> Editar Reservation:</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
    
        <form action="{% url 'hotel:update_reserva' reservation.id %}" method = 'POST'>
            {% csrf_token %}
            <div class="modal-body">           
            
            <div class="form-group m3">
                <label for="room">Room:</label>
                    <select class="form-control" id="room" name="room">
                        {% for room in rooms %}
                            {% if room.status == '#9bf0ac'  %}
                                <option value="{{ room.id }}" {% if room.name == reservation.room.name %}selected{% endif %} {% if room.state == 1 %}data-available{% endif %}>
                                    Room:  {{ room.name }} - Type: {{room.get_type_room_display }} || {{room.get_state_display}}
                                </option>
                            {% endif %}    
                        {% endfor %}
                    </select>
            </div>
        
                <div class="form-group m-3">
                    <label for="date_in">Date in:</label>
                    <input type="date" class="form-control" id="date_in" name="date_in" value={{reservation.date_in|date:'Y-m-d'}} readonly >
                </div>
                <div class="form-group m-3">
                    <label for="date_out">Date out:</label>
                    <input type="date" class="form-control" id="date_out" name="date_out" value={{reservation.date_out|date:'Y-m-d'}} >
                </div>

                <div class="form-group m-3">
                    <label for="amount_people">Amount people:</label>
                    <input type="number" class="form-control" id="amount_people" name="amount_people" value={{reservation.amount_people}} >
                </div>
                <div class="form-group m-3">
                    <label for="observations">Observation:</label>
                    <textarea name="observations" id=""  rows="10">{{reservation.observations}}</textarea>
                </div>

                    
            </div>


            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>

        </form>
        
      </div>
    </div>
</div>
{% endfor %}


{% endblock content %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ProjectHotel</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>
<body>
    



    <div class="container d-flex mt-5"> 
        <div class="row justify-content-center border rounded p-3" style="background-color: #D9D8D8">
            <div class="col">
                
                <div class='mb-5'>
                    <h1 >Welcome to ProjectHotel</h1>
                </div>

                <form action="" method='POST'>
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="">User:</label>
                        <input type="text" class='form-control' name='username' id='username' placeholder ='User...'>
                    </div>

                    <br>
                    <div class="form-group">
                        <label for="">Password:</label>
                        <input type="password" class='form-control' name='password' id='password' placeholder ='Password...'>
                    </div>

                    <br>                    
                    <button class="btn btn-success mr-4" type='submit'>Login</button>
                    <a href="{% url 'hotel:register' %}">Register</a>

                </form>
            </div>
        </div>
    </div>



    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="js/demo/chart-area-demo.js"></script>
    <script src="js/demo/chart-pie-demo.js"></script>


    {% include 'message.html' %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="sweetalert2.all.min.js"></script>
    <script src="sweetalert2.min.js"></script>
    <link rel="stylesheet" href="sweetalert2.min.css">
</body>

templates/message.html
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>


{% if messages %}
  {% for message in messages %}

      {% if message.tags == "success" %}
        <script>
          Swal.fire({
          "title" : "Acción Lograda Correctamente",
          "text" : "{{message}}",
          "icon" : "success"
          })
      </script>

      {% endif %}
      {% if message.tags ==  "error" %}

        <script>
          Swal.fire({
          "title" : "Inconveniente",
          "text" : "{{message}}",
          "icon" : "warning"
          })
      </script>
      {% endif %}


  {% endfor %}

{% endif %}

{% comment %} {% for message in messages %}
  <div class="mt-5 alert {% if message.tags == 'success'%}alert-success{%else%}alert-danger{%endif%}">
    {{ message }}
    <button type="button" class="close" data-bs-dismiss="alert">X</button>
  </div>
{% endfor %} {% endcomment %}

<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

{% if messages %}
  {% for message in messages %}
    {% if message.tags == 'success' %}
        <script>
          Swal.fire({
            'title' : 'Ok',
            'text' : '{{ message }}',
            'icon' : 'success',
          })
        </script>
    {% elif message.tags == 'error' %}
      <script>
        Swal.fire({
          'title' : 'Upsss!',
          'text' : '{{ message }}',
          'icon' : 'warning',
        })
      </script>
    {% endif %}
  {% endfor %}
{% endif %}

templates/rooms.html
{% extends 'base.html' %}


{% block content %}
<!--Room tables-->
<div class="row m-4 ">
    <div class="col d-flex justify-content-center flex-wrap">

        <table class="table table-bordered">
            <thead>
            <tr>
                <th class="col-4 ">Rooms:</th> 
                <th class="col-8">Status:</th>
            </tr>
            </thead>
            <tbody>
                <!--Iteration, each room has it's status and observation, bg second column shows the status -->
            {% for room in rooms %}
                <tr>
                <td class="col-4 text-center"><form action="" method='POST'>
                    {% csrf_token %}
                    <button type='button' class='btn btn-primary mx-4 my-4 px-5 ' data-bs-toggle="modal" data-bs-target="#updateModal_{{room.id}}">{{room.name}}</button>
                </form></td>

                <td class="col-8"style="background-color:{{room.status}}; color:black;">{{room.get_status_display}} - {{room.get_state_display}}<br>Motivo: {{room.observations}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>




<!--Modal Room -->
{% for room in rooms %}
<div class="modal fade" id="updateModal_{{room.id}}" tabindex="-1" aria-labelledby="exampleModalLabel{{room.id}}" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel"><i class="bi bi-journal-bookmark"></i> Edit room status:</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <!--Status Buttons function in utils.utils-->
        <div class="container-buttons col-8 mx-auto">
            <div class="checkout bg-success rounded pt-1 mt-4 mb-1 text-center" >
                <a href="{% url 'hotel:room_clean' pk=room.id %}"  class="mt-2 text-left"style="font-size:12px; font-weight:bold; color:#fff;">Clean</a>
            </div>
            <div class="checkout bg-warning rounded pt-1 my-1 text-center" >
                <a href="{% url 'hotel:room_dirty' pk=room.id %}"  class="mt-2 text-left"style="font-size:12px; font-weight:bold; color:#fff;">Dirty</a>
            </div>
            <div class="checkout bg-danger rounded pt-1 my-1 text-center mb-4" >
                <a href="{% url 'hotel:room_blocked' pk=room.id %}"  class="mt-2 text-left"style="font-size:12px; font-weight:bold; color:#fff;">Blocked</a>
            </div>
        </div>    

        <!--Observation form-->
        <form action="{% url 'hotel:update_room' room.id%}" method='POST'>      
            {% csrf_token %}
            <div class="form-group m3 ml-2">
                <label for="observations">Observations:</label>
                <textarea name="observations" id="observations" cols="30" rows="5" >{{room.observations}}</textarea>
            </div>


            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Save</button>
            </div>

        </form>

        
      </div>
    </div>
</div>
{% endfor %}

{% endblock content %}

templates/search.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="content">
    <div class="row">     
        <div class="col-12">
            <div class="table-responsive d-flex justify-content-center">
                <form action="{% url 'hotel:search'%}" method="get">
                    <table class="text-center">
                        <thead>
                            <tr>
                                <th>
                                    <label for="passanger">Passanger:</label>
                                </th>
                                <th>
                                    <label for="room">Room:</label>
                                </th>
                                <th>
                                    <label for="date_in">Date in:</label>
                                </th>
                                <th>
                                    <label for="date_out">Date out:</label>
                                </th>
                                <th>
                                    <label for="number">Res Num:</label>
                                </th>
                                <th>
                                    <label for="status_res">Status:</label>
                                </th>
                            </tr>
                            
                        </thead>

                        <tbody>
                            <td>
                                <input type="text" class="mr-2" list="passe" name="passanger"  placeholder="Dni..." style='max-width: 80px;'>
                                <datalist id="passe">
                                    {% for passanger in passangers %}
                                    <option value="{{passanger.id}}">{{passanger.name}} - {{passanger.dni}}</option>
                                    {% endfor %}
                                </datalist>  
                            </td>
                            <td>
                                {% render_field myFilter.form.room class="mr-2" %}
                            </td>
                            <td>
                                {%render_field myFilter.form.date_in type="date" style='max-width: 80px;' class="mr-2"%}
                            </td>
                            <td>
                                {%render_field myFilter.form.date_out type="date" style='max-width: 80px;' class="mr-2" %}
                            </td>
                            <td>
                                {% render_field myFilter.form.number style='max-width: 80px;' class="mr-2" %}
                            </td>
                            <td>
                                {{myFilter.form.status_res}}
                            </td>
                        </tbody>
                    </table>                      
                        
                    <div class="form-group text-center mt-4">
                        <button type="submit" class="btn btn-success ml-4" data-bs-toggle="modal" data-bs-target="#updateModal_{{reservation.id}}">
                            Search
                        </button>
                        <a href="{% url 'hotel:search' %}"><button type="button" class="btn btn-warning ml-4">Reset</button> </a>
                    </div>
                </form>
            </div>
            
            <div class="table-responsive">
            <table class="table table-bordered mt-3">
                <thead>
                <tr>
                    <th>Passanger:</th> 
                    <th>Res Num:</th>
                    <th>Room:</th>
                    <th>Room type:</th>
                    <th>Date in:</th>
                    <th>Date out:</th>
                    <th>Status res:</th>
                    <th>Pdf:</th>
                    <th>Till:</th>
                </tr>
                </thead>
                <tbody>
                    {% if request.GET %}
                        {% for reservation in reservations %}
                            <tr>
                                <td><a href="{% url 'hotel:passanger-data' pk=reservation.passanger.id %}">{{reservation.passanger}}</a></td>
                                <td class="text-center py-2">
                                    <div class="mt-2">
                                        {{reservation.number}}
                                        <form action="{% url 'hotel:search_update' pk=reservation.id %}" method="post" class="text-start">
                                            {% csrf_token %}
                                            <button type="button" class="btn btn-warning ml-4 text-center" data-bs-toggle="modal" data-bs-target="#updateModal_{{reservation.id}}">
                                                Edit
                                            </button>
                                        </form> 
                                    </div>
                                </td>
                                <td>{{reservation.room}}</td>
                                <td>{{reservation.get_type_res_display}}</td>
                                <td>{{reservation.date_in}}</td>
                                <td>{{reservation.date_out}}</td>
                                <td>{{reservation.get_status_res_display}}</td>
                                <td>
                                    {% if reservation.status_res == 1 %}
                                    <div class="checkout bg-success rounded pt-1 text-center" >
                                        <a href="{% url 'hotel:checkin' pk=reservation.id %}"  class=" text-left"style="font-size:12px; font-weight:bold; color:#fff;">Check-in</a>
                                    </div>
                                    <div class="checkout bg-danger rounded pt-1 text-center mt-2" >
                                        <a href="{% url 'hotel:noshow' pk=reservation.id %}"  class="text-left"style="font-size:12px; font-weight:bold; color:#fff;">No-show</a>
                                    </div>
                                    {% endif %}
                                    <div class="m-2">
                                        <a href="{% url 'hotel:export_pdf' pk=reservation.id %}" target="_blank">Open PDF</a>
                                    </div>
                                </td>
                                <td>
                                    {% for till in tills %}
                                        {% if till.till_res.number == reservation.number%}
                                            <a href="{% url 'caja:till' pk=reservation.id %}" class="btn btn-warning" target="_blank">
                                                Till
                                            </a>
                                        {% endif %}                                                           
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>                                 
            </table>
        </div>   
    </div>
</div>


<!--Reservation modal upate -->
{% for reservation in reservations %}
<div class="modal fade" id="updateModal_{{reservation.id}}" tabindex="-1" aria-labelledby="exampleModalLabel{{reservation.id}}" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel"><i class="bi bi-journal-bookmark"></i> Editar Reservation:</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
    
        <form action="{% url 'hotel:search_update' reservation.id %}" method = 'POST'>
            {% csrf_token %}
            <div class="modal-body">           
            
            <div class="form-group m3">
                <label for="room">Room:</label>
                    <select class="form-control" id="room" name="room">
                        <option value="">----</option>
                        {% for room in rooms %}
                            {% if room.status == '#9bf0ac' and room.state == 1 %}
                                <option value="{{ room.id }}">
                                  Room:  {{ room.name }} - Type: {{room.get_type_room_display}}
                                </option>
                            {% endif %}
                        {% endfor %}
                    </select>
            </div>
                <div class="form-group m-3">
                    <label for="date_in">Date in:</label>
                    <input type="date" class="form-control" id="date_in" name="date_in" value={{reservation.date_in|date:'Y-m-d'}} >
                </div>
                <div class="form-group m-3">
                    <label for="date_out">Date out:</label>
                    <input type="date" class="form-control" id="date_out" name="date_out" value={{reservation.date_out|date:'Y-m-d'}} >
                </div>
                <div class="form-group m-3">
                    <label for="amount_people">Amount people:</label>
                    <input type="number" class="form-control" id="amount_people" name="amount_people" value={{reservation.amount_people}} >
                </div>
                <div class="form-group m-3">
                    <label for="observations">Observation:</label>
                    <textarea name="observations" id=""  rows="10">{{reservation.observations}}</textarea>
                </div>

                    
            </div>


            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>

        </form>
        
      </div>
    </div>
</div>
{% endfor %}

{% endblock content %}